blank_issues_enabled: false
contact_links:
  - name: ReActor Node Community Support
    url: https://github.com/Gourieff/comfyui-reactor-node/discussions
    about: Please ask and answer questions here.
